In [1]:
import numpy as np

###Creating `10 x 10` array with random values

In [7]:
arr = np.random.rand(10, 10)

array([[0.99643443, 0.91827105, 0.26228153, 0.51841322, 0.95083351,
        0.90369016, 0.42945348, 0.74220931, 0.96476882, 0.24547302],
       [0.76184836, 0.43528893, 0.34296869, 0.95873798, 0.8170652 ,
        0.29915026, 0.66227214, 0.25345075, 0.51843363, 0.07779703],
       [0.70039018, 0.59792214, 0.32191514, 0.69639922, 0.14993789,
        0.19160636, 0.42279921, 0.24618236, 0.76252096, 0.46177265],
       [0.98181381, 0.67689169, 0.54858491, 0.38569606, 0.10034589,
        0.07534742, 0.75651249, 0.89531002, 0.84971558, 0.73628899],
       [0.02737265, 0.81625048, 0.7013345 , 0.49499234, 0.35157003,
        0.94428286, 0.6919266 , 0.78150555, 0.72755381, 0.45512427],
       [0.73828293, 0.47409002, 0.83669979, 0.17275726, 0.65187174,
        0.95177757, 0.73636327, 0.90660845, 0.01964053, 0.41973597],
       [0.48980837, 0.28218104, 0.28851969, 0.95121486, 0.48859909,
        0.59500378, 0.05730379, 0.11759071, 0.18307372, 0.58252946],
       [0.41486652, 0.85086583, 0.8161765

###Creating Array with

`Seed method`

In [11]:
np.random.seed(42)
arr_with_seed = np.random.rand(10, 10)
arr_with_seed

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497,
        0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998,
        0.78517596, 0.19967378, 0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159, 0.94888554, 0.96563203,
        0.80839735, 0.30461377, 0.09767211, 0.68423303, 0.44015249],
       [0.12203823, 0.49517691, 0.03438852, 0.9093204 , 0.25877998,
        0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446],
       [0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998,
        0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451,
        0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694],
       [0.77224477, 0.19871568, 0.0055221

###Slicing

In [12]:
A = arr_with_seed[:5, :7]
B = arr_with_seed[:7, :5]
C = arr_with_seed[:5, :7]

###Operations
- Addition
- Multiplication `matrix mulltiplication`

In [21]:
sum_a_c = A + C
prod_a_b = A @ B # np.dot(A, B) np.matmul(A, B) will result in same
sum_a_c, prod_a_b

(array([[0.74908024, 1.90142861, 1.46398788, 1.19731697, 0.31203728,
         0.31198904, 0.11616722],
        [0.04116899, 1.9398197 , 1.66488528, 0.42467822, 0.36364993,
         0.36680902, 0.60848449],
        [1.22370579, 0.27898772, 0.5842893 , 0.73272369, 0.91213997,
         1.57035192, 0.39934756],
        [1.2150897 , 0.34104825, 0.13010319, 1.89777107, 1.93126407,
         1.6167947 , 0.60922754],
        [0.24407647, 0.99035382, 0.06877704, 1.8186408 , 0.51755996,
         1.32504457, 0.62342215]]),
 array([[1.16430068, 1.69631643, 1.51842603, 1.5645091 , 1.29318442],
        [0.98428064, 1.42737889, 1.5101667 , 1.16272557, 1.0064413 ],
        [1.52792685, 1.70885196, 1.59200688, 2.03912199, 1.25140679],
        [1.86740273, 2.10130744, 1.71254166, 3.03425395, 1.89053973],
        [1.42450232, 1.48242565, 1.46040149, 1.99300521, 1.55348778]]))

### All possible **2D** pairs from `10 X 10` matrix

In [43]:
np.random.seed(43)
array = np.random.rand(10, 10)

empty_list = []

for i in range(1, 101):
  if 100 % i == 0:
    empty_list.append(array.reshape(i, 100 // i))

len(empty_list)

9

### All possible **3D** pairs from `10 X 10` matrix

In [46]:
empty_list = []

for i in range(1, 101):
  for j in range(1, 101):
    for k in range(1, 101):
      if (i * j * k) == 100:
        empty_list.append(array.reshape((i, j, k)))

len(empty_list)

36